//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassThePen.PassThePenService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] profileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] profileImage {
            get {
                return this.profileImageField;
            }
            set {
                if ((object.ReferenceEquals(this.profileImageField, value) != true)) {
                    this.profileImageField = value;
                    this.RaisePropertyChanged("profileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PassThePenService.IPlayerMgt")]
    public interface IPlayerMgt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/AddPlayer", ReplyAction="http://tempuri.org/IPlayerMgt/AddPlayerResponse")]
        int AddPlayer(PassThePen.PassThePenService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/AddPlayer", ReplyAction="http://tempuri.org/IPlayerMgt/AddPlayerResponse")]
        System.Threading.Tasks.Task<int> AddPlayerAsync(PassThePen.PassThePenService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/AutenticatePlayer", ReplyAction="http://tempuri.org/IPlayerMgt/AutenticatePlayerResponse")]
        int AutenticatePlayer(PassThePen.PassThePenService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/AutenticatePlayer", ReplyAction="http://tempuri.org/IPlayerMgt/AutenticatePlayerResponse")]
        System.Threading.Tasks.Task<int> AutenticatePlayerAsync(PassThePen.PassThePenService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/AutenticateEmail", ReplyAction="http://tempuri.org/IPlayerMgt/AutenticateEmailResponse")]
        int AutenticateEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/AutenticateEmail", ReplyAction="http://tempuri.org/IPlayerMgt/AutenticateEmailResponse")]
        System.Threading.Tasks.Task<int> AutenticateEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/UpdateDataPlayer", ReplyAction="http://tempuri.org/IPlayerMgt/UpdateDataPlayerResponse")]
        bool UpdateDataPlayer(string username, PassThePen.PassThePenService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/UpdateDataPlayer", ReplyAction="http://tempuri.org/IPlayerMgt/UpdateDataPlayerResponse")]
        System.Threading.Tasks.Task<bool> UpdateDataPlayerAsync(string username, PassThePen.PassThePenService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/GetDataPlayer", ReplyAction="http://tempuri.org/IPlayerMgt/GetDataPlayerResponse")]
        PassThePen.PassThePenService.Player GetDataPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/GetDataPlayer", ReplyAction="http://tempuri.org/IPlayerMgt/GetDataPlayerResponse")]
        System.Threading.Tasks.Task<PassThePen.PassThePenService.Player> GetDataPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/UpdatePlayerPassword", ReplyAction="http://tempuri.org/IPlayerMgt/UpdatePlayerPasswordResponse")]
        bool UpdatePlayerPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/UpdatePlayerPassword", ReplyAction="http://tempuri.org/IPlayerMgt/UpdatePlayerPasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePlayerPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/CodeEmail", ReplyAction="http://tempuri.org/IPlayerMgt/CodeEmailResponse")]
        int CodeEmail(string to, string affair, int validationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/CodeEmail", ReplyAction="http://tempuri.org/IPlayerMgt/CodeEmailResponse")]
        System.Threading.Tasks.Task<int> CodeEmailAsync(string to, string affair, int validationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/UpdatePassword", ReplyAction="http://tempuri.org/IPlayerMgt/UpdatePasswordResponse")]
        int UpdatePassword(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerMgt/UpdatePassword", ReplyAction="http://tempuri.org/IPlayerMgt/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<int> UpdatePasswordAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerMgtChannel : PassThePen.PassThePenService.IPlayerMgt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerMgtClient : System.ServiceModel.ClientBase<PassThePen.PassThePenService.IPlayerMgt>, PassThePen.PassThePenService.IPlayerMgt {
        
        public PlayerMgtClient() {
        }
        
        public PlayerMgtClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerMgtClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerMgtClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerMgtClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddPlayer(PassThePen.PassThePenService.Player player) {
            return base.Channel.AddPlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> AddPlayerAsync(PassThePen.PassThePenService.Player player) {
            return base.Channel.AddPlayerAsync(player);
        }
        
        public int AutenticatePlayer(PassThePen.PassThePenService.Player player) {
            return base.Channel.AutenticatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> AutenticatePlayerAsync(PassThePen.PassThePenService.Player player) {
            return base.Channel.AutenticatePlayerAsync(player);
        }
        
        public int AutenticateEmail(string email) {
            return base.Channel.AutenticateEmail(email);
        }
        
        public System.Threading.Tasks.Task<int> AutenticateEmailAsync(string email) {
            return base.Channel.AutenticateEmailAsync(email);
        }
        
        public bool UpdateDataPlayer(string username, PassThePen.PassThePenService.Player player) {
            return base.Channel.UpdateDataPlayer(username, player);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDataPlayerAsync(string username, PassThePen.PassThePenService.Player player) {
            return base.Channel.UpdateDataPlayerAsync(username, player);
        }
        
        public PassThePen.PassThePenService.Player GetDataPlayer(string username) {
            return base.Channel.GetDataPlayer(username);
        }
        
        public System.Threading.Tasks.Task<PassThePen.PassThePenService.Player> GetDataPlayerAsync(string username) {
            return base.Channel.GetDataPlayerAsync(username);
        }
        
        public bool UpdatePlayerPassword(string username, string password) {
            return base.Channel.UpdatePlayerPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePlayerPasswordAsync(string username, string password) {
            return base.Channel.UpdatePlayerPasswordAsync(username, password);
        }
        
        public int CodeEmail(string to, string affair, int validationCode) {
            return base.Channel.CodeEmail(to, affair, validationCode);
        }
        
        public System.Threading.Tasks.Task<int> CodeEmailAsync(string to, string affair, int validationCode) {
            return base.Channel.CodeEmailAsync(to, affair, validationCode);
        }
        
        public int UpdatePassword(string email, string password) {
            return base.Channel.UpdatePassword(email, password);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePasswordAsync(string email, string password) {
            return base.Channel.UpdatePasswordAsync(email, password);
        }
    }
}
