//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassThePen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Challenge {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Challenge() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassThePen.Properties.Challenge", typeof(Challenge).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja con tu mano no dominante (Dibujo libre).
        /// </summary>
        public static string Challenge1 {
            get {
                return ResourceManager.GetString("Challenge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  .
        /// </summary>
        public static string Challenge10 {
            get {
                return ResourceManager.GetString("Challenge10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja con tus ojos cerrados (Dibujo libre).
        /// </summary>
        public static string Challenge2 {
            get {
                return ResourceManager.GetString("Challenge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza dibujar cuando queden 10 segundos (Dibujo libre).
        /// </summary>
        public static string Challenge3 {
            get {
                return ResourceManager.GetString("Challenge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja solo con lineas rectas (Dibujo libre).
        /// </summary>
        public static string Challenge4 {
            get {
                return ResourceManager.GetString("Challenge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja a tu crush.
        /// </summary>
        public static string Challenge5 {
            get {
                return ResourceManager.GetString("Challenge5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja solo con puntos (Dibujo libre).
        /// </summary>
        public static string Challenge6 {
            get {
                return ResourceManager.GetString("Challenge6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja con un solo trazo (Dibujo libre).
        /// </summary>
        public static string Challenge7 {
            get {
                return ResourceManager.GetString("Challenge7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja lo más pequeño que puedas (Dibujo libre).
        /// </summary>
        public static string Challenge8 {
            get {
                return ResourceManager.GetString("Challenge8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibuja a tu personaje de ficción favorito.
        /// </summary>
        public static string Challenge9 {
            get {
                return ResourceManager.GetString("Challenge9", resourceCulture);
            }
        }
    }
}
