//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassThePen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Deck {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deck() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassThePen.Properties.Deck", typeof(Deck).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perro.
        /// </summary>
        public static string Card1 {
            get {
                return ResourceManager.GetString("Card1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automovil.
        /// </summary>
        public static string Card10 {
            get {
                return ResourceManager.GetString("Card10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card100 {
            get {
                return ResourceManager.GetString("Card100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motocicleta.
        /// </summary>
        public static string Card11 {
            get {
                return ResourceManager.GetString("Card11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bicicleta.
        /// </summary>
        public static string Card12 {
            get {
                return ResourceManager.GetString("Card12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autobus.
        /// </summary>
        public static string Card13 {
            get {
                return ResourceManager.GetString("Card13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avión.
        /// </summary>
        public static string Card14 {
            get {
                return ResourceManager.GetString("Card14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Helicóptero.
        /// </summary>
        public static string Card15 {
            get {
                return ResourceManager.GetString("Card15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arbol.
        /// </summary>
        public static string Card16 {
            get {
                return ResourceManager.GetString("Card16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rosa.
        /// </summary>
        public static string Card17 {
            get {
                return ResourceManager.GetString("Card17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reloj.
        /// </summary>
        public static string Card18 {
            get {
                return ResourceManager.GetString("Card18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collar.
        /// </summary>
        public static string Card19 {
            get {
                return ResourceManager.GetString("Card19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gato.
        /// </summary>
        public static string Card2 {
            get {
                return ResourceManager.GetString("Card2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casa.
        /// </summary>
        public static string Card20 {
            get {
                return ResourceManager.GetString("Card20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edificio.
        /// </summary>
        public static string Card21 {
            get {
                return ResourceManager.GetString("Card21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaca.
        /// </summary>
        public static string Card22 {
            get {
                return ResourceManager.GetString("Card22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paraguas.
        /// </summary>
        public static string Card23 {
            get {
                return ResourceManager.GetString("Card23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sillon.
        /// </summary>
        public static string Card24 {
            get {
                return ResourceManager.GetString("Card24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llaves.
        /// </summary>
        public static string Card25 {
            get {
                return ResourceManager.GetString("Card25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engranaje.
        /// </summary>
        public static string Card26 {
            get {
                return ResourceManager.GetString("Card26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antena.
        /// </summary>
        public static string Card27 {
            get {
                return ResourceManager.GetString("Card27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inyección.
        /// </summary>
        public static string Card28 {
            get {
                return ResourceManager.GetString("Card28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctor.
        /// </summary>
        public static string Card29 {
            get {
                return ResourceManager.GetString("Card29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Barco.
        /// </summary>
        public static string Card3 {
            get {
                return ResourceManager.GetString("Card3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taladro.
        /// </summary>
        public static string Card30 {
            get {
                return ResourceManager.GetString("Card30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martillo.
        /// </summary>
        public static string Card31 {
            get {
                return ResourceManager.GetString("Card31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Silla.
        /// </summary>
        public static string Card32 {
            get {
                return ResourceManager.GetString("Card32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ratón.
        /// </summary>
        public static string Card33 {
            get {
                return ResourceManager.GetString("Card33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventilador.
        /// </summary>
        public static string Card34 {
            get {
                return ResourceManager.GetString("Card34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parque.
        /// </summary>
        public static string Card35 {
            get {
                return ResourceManager.GetString("Card35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amor.
        /// </summary>
        public static string Card36 {
            get {
                return ResourceManager.GetString("Card36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microondas.
        /// </summary>
        public static string Card37 {
            get {
                return ResourceManager.GetString("Card37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microscopio.
        /// </summary>
        public static string Card38 {
            get {
                return ResourceManager.GetString("Card38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lago.
        /// </summary>
        public static string Card39 {
            get {
                return ResourceManager.GetString("Card39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paloma.
        /// </summary>
        public static string Card4 {
            get {
                return ResourceManager.GetString("Card4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playa.
        /// </summary>
        public static string Card40 {
            get {
                return ResourceManager.GetString("Card40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string Card41 {
            get {
                return ResourceManager.GetString("Card41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estufa.
        /// </summary>
        public static string Card42 {
            get {
                return ResourceManager.GetString("Card42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concierto.
        /// </summary>
        public static string Card43 {
            get {
                return ResourceManager.GetString("Card43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leon.
        /// </summary>
        public static string Card44 {
            get {
                return ResourceManager.GetString("Card44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elefante.
        /// </summary>
        public static string Card45 {
            get {
                return ResourceManager.GetString("Card45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cocodrilo.
        /// </summary>
        public static string Card46 {
            get {
                return ResourceManager.GetString("Card46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bateria.
        /// </summary>
        public static string Card47 {
            get {
                return ResourceManager.GetString("Card47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guitarra.
        /// </summary>
        public static string Card48 {
            get {
                return ResourceManager.GetString("Card48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saxofón.
        /// </summary>
        public static string Card49 {
            get {
                return ResourceManager.GetString("Card49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pera.
        /// </summary>
        public static string Card5 {
            get {
                return ResourceManager.GetString("Card5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lampara.
        /// </summary>
        public static string Card50 {
            get {
                return ResourceManager.GetString("Card50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perezoso.
        /// </summary>
        public static string Card51 {
            get {
                return ResourceManager.GetString("Card51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Champiñones.
        /// </summary>
        public static string Card52 {
            get {
                return ResourceManager.GetString("Card52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pollo.
        /// </summary>
        public static string Card53 {
            get {
                return ResourceManager.GetString("Card53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planeta.
        /// </summary>
        public static string Card54 {
            get {
                return ResourceManager.GetString("Card54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estrella.
        /// </summary>
        public static string Card55 {
            get {
                return ResourceManager.GetString("Card55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cometa.
        /// </summary>
        public static string Card56 {
            get {
                return ResourceManager.GetString("Card56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadena.
        /// </summary>
        public static string Card57 {
            get {
                return ResourceManager.GetString("Card57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto.
        /// </summary>
        public static string Card58 {
            get {
                return ResourceManager.GetString("Card58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hamburguesa.
        /// </summary>
        public static string Card59 {
            get {
                return ResourceManager.GetString("Card59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uvas.
        /// </summary>
        public static string Card6 {
            get {
                return ResourceManager.GetString("Card6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velero.
        /// </summary>
        public static string Card60 {
            get {
                return ResourceManager.GetString("Card60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libro.
        /// </summary>
        public static string Card61 {
            get {
                return ResourceManager.GetString("Card61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manzana.
        /// </summary>
        public static string Card62 {
            get {
                return ResourceManager.GetString("Card62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Araña.
        /// </summary>
        public static string Card63 {
            get {
                return ResourceManager.GetString("Card63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tanque.
        /// </summary>
        public static string Card64 {
            get {
                return ResourceManager.GetString("Card64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ballena.
        /// </summary>
        public static string Card65 {
            get {
                return ResourceManager.GetString("Card65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internet.
        /// </summary>
        public static string Card66 {
            get {
                return ResourceManager.GetString("Card66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tortuga.
        /// </summary>
        public static string Card67 {
            get {
                return ResourceManager.GetString("Card67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pirata.
        /// </summary>
        public static string Card68 {
            get {
                return ResourceManager.GetString("Card68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soldado.
        /// </summary>
        public static string Card69 {
            get {
                return ResourceManager.GetString("Card69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taza.
        /// </summary>
        public static string Card7 {
            get {
                return ResourceManager.GetString("Card7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        public static string Card70 {
            get {
                return ResourceManager.GetString("Card70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tigre.
        /// </summary>
        public static string Card71 {
            get {
                return ResourceManager.GetString("Card71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cama.
        /// </summary>
        public static string Card72 {
            get {
                return ResourceManager.GetString("Card72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Card73 {
            get {
                return ResourceManager.GetString("Card73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lápida.
        /// </summary>
        public static string Card74 {
            get {
                return ResourceManager.GetString("Card74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mecanico.
        /// </summary>
        public static string Card75 {
            get {
                return ResourceManager.GetString("Card75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card76 {
            get {
                return ResourceManager.GetString("Card76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card77 {
            get {
                return ResourceManager.GetString("Card77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card78 {
            get {
                return ResourceManager.GetString("Card78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card79 {
            get {
                return ResourceManager.GetString("Card79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Televisión.
        /// </summary>
        public static string Card8 {
            get {
                return ResourceManager.GetString("Card8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card80 {
            get {
                return ResourceManager.GetString("Card80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card81 {
            get {
                return ResourceManager.GetString("Card81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card82 {
            get {
                return ResourceManager.GetString("Card82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card83 {
            get {
                return ResourceManager.GetString("Card83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card84 {
            get {
                return ResourceManager.GetString("Card84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card85 {
            get {
                return ResourceManager.GetString("Card85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card86 {
            get {
                return ResourceManager.GetString("Card86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card87 {
            get {
                return ResourceManager.GetString("Card87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card88 {
            get {
                return ResourceManager.GetString("Card88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card89 {
            get {
                return ResourceManager.GetString("Card89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Computadora.
        /// </summary>
        public static string Card9 {
            get {
                return ResourceManager.GetString("Card9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card90 {
            get {
                return ResourceManager.GetString("Card90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card91 {
            get {
                return ResourceManager.GetString("Card91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card92 {
            get {
                return ResourceManager.GetString("Card92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card93 {
            get {
                return ResourceManager.GetString("Card93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card94 {
            get {
                return ResourceManager.GetString("Card94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card95 {
            get {
                return ResourceManager.GetString("Card95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card96 {
            get {
                return ResourceManager.GetString("Card96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card97 {
            get {
                return ResourceManager.GetString("Card97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card98 {
            get {
                return ResourceManager.GetString("Card98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        public static string Card99 {
            get {
                return ResourceManager.GetString("Card99", resourceCulture);
            }
        }
    }
}
