//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassThePen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassThePen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string ChangePassword_Cancel_Button {
            get {
                return ResourceManager.GetString("ChangePassword_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string ChangePassword_ChangePassword_Label {
            get {
                return ResourceManager.GetString("ChangePassword_ChangePassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        public static string ChangePassword_ConfirmPassword_Label {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string ChangePassword_Invalid_Fields_Label {
            get {
                return ResourceManager.GetString("ChangePassword_Invalid_Fields_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        public static string ChangePassword_NewPassword_Label {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string ChangePassword_SavePassword_Button {
            get {
                return ResourceManager.GetString("ChangePassword_SavePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificar.
        /// </summary>
        public static string DrawReview_Submit_Button {
            get {
                return ResourceManager.GetString("DrawReview_Submit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Califica los dibujos.
        /// </summary>
        public static string DrawReview_Title_Label {
            get {
                return ResourceManager.GetString("DrawReview_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Global_Cancel_Button {
            get {
                return ResourceManager.GetString("Global_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo .
        /// </summary>
        public static string Global_Email_Label {
            get {
                return ResourceManager.GetString("Global_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de caracteres excedidos. Numero maximo: 50.
        /// </summary>
        public static string Global_Error__LastName_Label {
            get {
                return ResourceManager.GetString("Global_Error__LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor de revisar el formato de su correo electronico.
        /// </summary>
        public static string Global_Error_Email_Label {
            get {
                return ResourceManager.GetString("Global_Error_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de caracteres excedidos. Numero maximo: 50.
        /// </summary>
        public static string Global_Error_Name_Label {
            get {
                return ResourceManager.GetString("Global_Error_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener: *, +, @, #, $, %. Una mayuscula y un numero. Longitud entre 8-16..
        /// </summary>
        public static string Global_Error_Password_Label {
            get {
                return ResourceManager.GetString("Global_Error_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no son iguales.
        /// </summary>
        public static string Global_Error_Repit_Password {
            get {
                return ResourceManager.GetString("Global_Error_Repit_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de caracteres excedidos. Numero maximo: 20.
        /// </summary>
        public static string Global_Error_Username_Label {
            get {
                return ResourceManager.GetString("Global_Error_Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Global_Label_Password {
            get {
                return ResourceManager.GetString("Global_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar.
        /// </summary>
        public static string Global_Resend_Button {
            get {
                return ResourceManager.GetString("Global_Resend_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Global_Send_Button {
            get {
                return ResourceManager.GetString("Global_Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Global_Username_Label {
            get {
                return ResourceManager.GetString("Global_Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string Login_Forgot_Password_Button {
            get {
                return ResourceManager.GetString("Login_Forgot_Password_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión como invitado.
        /// </summary>
        public static string Login_GuestClic_Label {
            get {
                return ResourceManager.GetString("Login_GuestClic_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Login_Login_Button {
            get {
                return ResourceManager.GetString("Login_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string Login_Login_tittle {
            get {
                return ResourceManager.GetString("Login_Login_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate aquí.
        /// </summary>
        public static string Login_New_Player_Button {
            get {
                return ResourceManager.GetString("Login_New_Player_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Aun no tienes una cuenta?.
        /// </summary>
        public static string Login_New_Player_Label {
            get {
                return ResourceManager.GetString("Login_New_Player_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Main_Add_Button {
            get {
                return ResourceManager.GetString("Main_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string MainManu_FriendList_Label {
            get {
                return ResourceManager.GetString("MainManu_FriendList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del juego.
        /// </summary>
        public static string MainMenu_ExitGame_Button {
            get {
                return ResourceManager.GetString("MainMenu_ExitGame_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string MainMenu_FriendRequests_Button {
            get {
                return ResourceManager.GetString("MainMenu_FriendRequests_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenu_Friends_Button {
            get {
                return ResourceManager.GetString("MainMenu_Friends_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenu_Friends_Label {
            get {
                return ResourceManager.GetString("MainMenu_Friends_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string MainMenu_FriendsRequests_Label {
            get {
                return ResourceManager.GetString("MainMenu_FriendsRequests_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú de juego.
        /// </summary>
        public static string MainMenu_GameMenu_Label {
            get {
                return ResourceManager.GetString("MainMenu_GameMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar!.
        /// </summary>
        public static string MainMenu_Play_Button {
            get {
                return ResourceManager.GetString("MainMenu_Play_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibujo Actual.
        /// </summary>
        public static string Match_CurrentDraw_Label {
            get {
                return ResourceManager.GetString("Match_CurrentDraw_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje.
        /// </summary>
        public static string Match_Score_Label {
            get {
                return ResourceManager.GetString("Match_Score_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje:.
        /// </summary>
        public static string Match_ScorePlayer_Label {
            get {
                return ResourceManager.GetString("Match_ScorePlayer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Turno.
        /// </summary>
        public static string Match_StartTurn_Button {
            get {
                return ResourceManager.GetString("Match_StartTurn_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo Restante.
        /// </summary>
        public static string Match_TimeRemaining_Label {
            get {
                return ResourceManager.GetString("Match_TimeRemaining_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno Actual.
        /// </summary>
        public static string Match_Turn_Label {
            get {
                return ResourceManager.GetString("Match_Turn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Profile_Cancel_Button {
            get {
                return ResourceManager.GetString("Profile_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string Profile_ChangePassword_Button {
            get {
                return ResourceManager.GetString("Profile_ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string Profile_CurrentPassword_Label {
            get {
                return ResourceManager.GetString("Profile_CurrentPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string Profile_Email_Label {
            get {
                return ResourceManager.GetString("Profile_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese toda la información.
        /// </summary>
        public static string Profile_Invalid_Fields_Label {
            get {
                return ResourceManager.GetString("Profile_Invalid_Fields_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Profile_LastName_Label {
            get {
                return ResourceManager.GetString("Profile_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Profile_Name_Label {
            get {
                return ResourceManager.GetString("Profile_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Profile_SaveProfile_Button {
            get {
                return ResourceManager.GetString("Profile_SaveProfile_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        public static string Profile_Username_Label {
            get {
                return ResourceManager.GetString("Profile_Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string RecoverPassword_Change_Button {
            get {
                return ResourceManager.GetString("RecoverPassword_Change_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el código de validación .
        /// </summary>
        public static string RecoverPassword_Code_Label {
            get {
                return ResourceManager.GetString("RecoverPassword_Code_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduca su nueva contraseña.
        /// </summary>
        public static string RecoverPassword_NewPassword_Label {
            get {
                return ResourceManager.GetString("RecoverPassword_NewPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba de nuevo su contraseña.
        /// </summary>
        public static string RecoverPassword_RepitPassword_Label {
            get {
                return ResourceManager.GetString("RecoverPassword_RepitPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string RecoverPassword_Title_Label {
            get {
                return ResourceManager.GetString("RecoverPassword_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        public static string RecoverPassword_Valid_Button {
            get {
                return ResourceManager.GetString("RecoverPassword_Valid_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Register_LastName_Label {
            get {
                return ResourceManager.GetString("Register_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string Register_Name_Label {
            get {
                return ResourceManager.GetString("Register_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Register_Nickname_Label {
            get {
                return ResourceManager.GetString("Register_Nickname_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string Register_Register_Button {
            get {
                return ResourceManager.GetString("Register_Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string Register_Repeat_Password {
            get {
                return ResourceManager.GetString("Register_Repeat_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar nuevo usuario.
        /// </summary>
        public static string Register_tittle {
            get {
                return ResourceManager.GetString("Register_tittle", resourceCulture);
            }
        }
    }
}
